name: Build
main: me.ES96.com.Build
version: 1.0.1
description: Plugin that manages all build administrative features.
website: https://github.com/ES359
author: ES96

commands:
  build:
    description: Main command for this plugin.
    aliases: [set, bd, bld]
  warp:
    description: Warp command.
  list:
    description: List command.
  setwarp:
    description: Sets a warps.
    aliases: [swarp, sw]
  deletewarp:
    description: Deletes a warps.
    aliases: [delwarp, dw]
  spawn:
    description: Teleports to spawn.
  setspawn:
    description: Sets the spawn for that world.
    aliases: [bsp,sspawn]
  tp:
    description: Teleports to a player
    aliases: [teleport]
  tptoggle:
    description: Toggles weither or not a player wants tp requests.
    aliases: [tpt,toggle]
  tphere:
    description: Main command for tphere.
    aliases: [call]
  chat:
    description: Chat command.
    aliases: [talk,c,shutup]
  kick:
    description: Main command for kicking.
  help:
    description: Main command for this gui.
  item:
    description: Main command for spawning items.
    aliases: [i]
  clearinventory:
    description: Clears the players inventory.
    aliases: [ci,cl,clinv,clinventory,inventoryclear]
  cmddisable:
    description: Administration command for CMD-Disable
    aliases: [cmd, cdisable, cd]
  whitelist:
    description: Modified  whitelist command.
    aliases: [wl]
  message:
    description: private message command
    aliases: [msg,pm,hi,whatsup,sup]
  mode:
    description: Command to change players mode on the server.
    aliases: [gm]
  inventory:
    description: Command to view into other players inventories.
    aliases: [invsee,inv,view]
  map:
    description: Command to view maps...
  data:
    description: Command to view data.
permissions:

  Build.*:
    description: Gives access completely to Build plugin.
    children:
      Build.set.*: true
      Build.command.*: true
      Build.bypass.*: true
      Build.mode.*: true
      Build.gamemodes.*: true

  Build.set.*:
    description: Access to set flag.
    children:
      Build.set.build: true
      Build.set.break: true
      Build.set.place: true
      Build.set.interact: true
      Build.set.drop: true
      Build.set.pickup: true
      Build.warp.set: true
      Build.set.chat: true
      Build.set.tnt: true
      Build.mode.set: true
  Build.mod:
    description: Given to moderators...
    children:
      Build.tp: true
      Build.tphere: true
      Build.tptoggle: true
      Build.vanish: true
      Build.mode.*: true
      Build.world.kick: true
      Build.chat.clear: true
      Build.whitelist.notify: true
      Build.chat.clearothers: true


  Build.member:
    description: Given to trusted memebers on the server.
    children:
      Build.mode.survival: true
      Build.mode.creative: true
      Build.mode.adventure: true
      Build.chat: true
      Build.chat.clearself: true
      Build.warp.list: true
      Build.ci: true

  Build.guest:
    description: Usually given to guest users on build server...
    children:
      Build.spawn: true
      Build.warp: true
      Build.heal: true
      Build.message: true
      Build.help: true
      Build.mode.set: true
      Build.mode.survival: true
      Build.mode.creative: true
      Build.chat: true
      Build.list: true

  Build.mode.*:
    description: Access to all mode changing permissions
    children:
      Build.mode.set: true
      Build.toggle: true
      Build.toggle.buildmode: true
      Build.mode.set.others: true
      Build.mode.survival: true
      Build.mode.creative: true
      Build.mode.adventure: true
      Build.mode.spectator: true
      Build.users: true

  Build.gamemodes.*:
    description:
    children:
      Build.mode.set.others: true
      Build.mode.survival: true
      Build.mode.survival: true
      Build.mode.adventure: true
      Build.mode.spectator: true

  Build.command.*:
    description: Access to Build commands.
    children:
      Build.set: true
      Build.tp: true
      Build.tphere: true
      Build.tptoggle: true
      Build.warp: true
      Build.warp.list: true
      Build.warp.delete: true
      Build.world.kick: true
      Build.setspawn: true
      Build.delspawn: true
      Build.spawn: true
      Build.whitelist.notify: true
      Build.whitelist: true
      Build.staffchat: true
      Build.heal: true
      Build.help: true
      Build.chat: true
      Build.chat.clearself: true
      Build.chat.clear: true
      Build.reload: true
      Build.toggle.buildmode: true
      Build.toggle: true
      Build.message: true
      Build.mode.set: true
      Build.mode.set.others: true
      Build.ci: true
      Build.users: true
      Build.item: true
  Build.bypass.*:
    description: Access to bypass permissions.
    children:
      Build.bypass.chat: true
      Build.bypass.place: true
      Build.bypass.break: true
      Build.bypass.interact: true
      Build.bypass.drop: true
      Build.bypass.pickup: true
      Build.bypass.toggle: true
  Build.spawn:
    description: Main command to return to spawn.
    default: true
  Build.help:
    description: Main command for help
    default: true